### ISSUE TITLE
Device properties or child device trees might be overwritten.

### ISSUE THREAD

**Issue by udoschneider** [nerves-project/nerves_runtime#156]
nerves_runtime uses a nested map for storing uevent data. If however a child devpath part has the same name as a property key it might get overwritten. There are two cases (depending on whether the child or parent event is received first):

IF a (direct) child device's devpath part is the same as an existing property in the parent
AND the child is added after the parent
THEN the parent key property will be overwritten.
    
IF a (direct) child device's devpath part is the same as an existing property in the parent
AND the parent  is added after the child
THEN the child(ren) are replaced by the parent property.

Please note that both cases can only happen if the devpath part has the same name as the property key. This however is outside of nerves_runtime's scope as the event data is defined by Linux. By checking the Linux source very briefly I didn't find any guarantee that this cannot happen. So it's very unlikely but not impossible ...

Test cases are in my branch under https://github.com/krodelin/nerves_runtime/blob/0198186cdfe3bf5f8d2f1b262468cf9b708d46ba/test/uevent_test.exs#L58-L76

**Comment by fhunleth** [comment]
Closing old issues. Please comment if you'd like to revisit.
