### ISSUE TITLE
crng is slow to initialize on devices where rngd finds no entropy sources

### ISSUE THREAD

**Issue by trarbr** [nerves-project/nerves_runtime#166]
### Environment

* Elixir version (`elixir -v`): 1.8.1
* Nerves environment: (`mix nerves.env --info`)

```
|nerves_bootstrap| Environment Package List

  Pkg:         kit_x86_64
  Vsn:         1.9.0
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Docker, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.5.0
  Type:        toolchain_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_x86_64_unknown_linux_gnu
  Vsn:         1.1.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_system_br
  Vsn:         1.7.1
  Type:        system_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start

Nerves environment
  MIX_TARGET:   intel_STK1A32SC
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     intel_STK1A32SC
  toolchain:  /Users/troels/.nerves/artifacts/nerves_toolchain_x86_64_unknown_linux_gnu-darwin_x86_64-1.1.0
  system:     /Users/troels/.nerves/artifacts/kit_x86_64-portable-1.9.0
```

* Additional information about your host, target hardware or environment that
  may help

### Current behavior

I'm working on porting Nerves to the NanoPi Neo2. `rngd` fails to start on this board (more info in  [the issue on the system repo](https://github.com/uptimedk/nerves_system_nanopi_neo2/issues/8)) because it finds no sources of entropy. As a result, `crng` is very slow to initialize, usually taking 3 - 4 minutes.

From what I can find, the usual remedy to these kinds of situations is to use Haveged instead, which can also generate entropy. There's some uncertainty about how secure that is, but I can tell from experiments that it certainly speeds things up (`crng` is now initialized in less than 20 seconds).

Setting `BR2_PACKAGE_HAVEGED=y` adds a binary at `/usr/sbin/haveged` which works much like `rngd` - it forks and runs as a daemon in the background.

### Expected behavior

If `rngd` fails to start (or has not been included in the system), nerves_runtime should try starting `haveged` as a fallback. This will enable systems to opt-in to this potentially-weak entropy source by setting  `BR2_PACKAGE_HAVEGED=y` in nerves_defconfig.

**Comment by fhunleth** [comment]
Starting `haveged` as a fallback after `rngd` seems reasonable to me. If you want to send a PR, I'll merge it.

**Comment by trarbr** [comment]
:+1: I have a proposal ready, will submit it after testing it on Monday
