### ISSUE TITLE
An application boot failure around KmsgTailer after update from nerves_runtime  v0.8.0 to v0.11.0

### ISSUE THREAD

**Issue by metelik** [nerves-project/nerves_runtime#174]
#62 # Environment
Build host: Linux ubuntu 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Target: Linux smartslot 4.19.72 #4 SMP PREEMPT Thu Mar 12 07:38:25 PDT 2020 armv7l GNU/Linux

nerves: 1.6.0
nerves_bootstrap: ~> 1.8

* Elixir version (`elixir -v`):
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.10.0 (compiled with Erlang/OTP 22)

* Nerves environment: (`mix nerves.env --info`)
nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_poky
  Vsn:         2.7.1-5
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_system_yocto
  Vsn:         1.0.0
  Type:        system_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start

Nerves environment
  MIX_TARGET:   lces2
  MIX_ENV:      dev

NERVES_TOOLCHAIN is unset
_|nerves_bootstrap| Environment Variable List
  target:     lces2
  toolchain:  /home/motyl/.local/share/nerves/artifacts/nerves_system_poky-portable-2.7.1-5/toolchain/sysroots/x86_64-pokysdk-linux
  system:     /home/motyl/.local/share/nerves/artifacts/nerves_system_poky-portable-2.7.1-5/toolchain/sysroots/armv7vet2hf-vfpv4d16-poky-linux-gnueabi/../../../
  app:        /mnt/src/agilis_fw/firmware.cr4

|nerves_bootstrap| Loadpaths End_

* Additional information about your host, target hardware or environment that
  may help

### Current behavior
Boot Failed::nerves_runtime exited from {{:shutdown, {:failed_to_start_child, Nerves.Runtime.Log.KmsgTailer, {:enoent, [{:erlang, :open_port, [{:spawn_executable, '/srv/erlang/lib/nerves_runtime-0.11.0/priv/nerves_runtime'}, [{:arg0, "kmsg_tailer"}, {:line, 1024}, :use_stdio, :binary, :exit_status]], []}, {Nerves.Runtime.Log.KmsgTailer, :init, 1, [file: 'lib/nerves_runtime/log/kmsg_tailer.ex', line: 22]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}, {Nerves.Runtime.Application, :start, [:normal, []]}}

**Comment by fhunleth** [comment]
This looks like your custom toolchain created a binary that can't load. It's probably a missing shared library or an architecture mismatch. I think this is the first executable built from your app (not when building the system) that gets run.
