### ISSUE TITLE
Cannot run iex session

### ISSUE THREAD

**Issue by stormpat** [nerves-project/nerves_runtime#2]
I started a fresh project with mix nerves.new and when i try to run the application within an iex session the nerves_runtime fails. When i remove nerves runtime from the mixfile all is good. The link to the docs site seems to be down, so i could not find a way to run the app locally with iex.

**Comment by mobileoverlord** [comment]
nerves runtime requires linux to run locally. It should be isolated to be included in only the target runtime of a nerves project. We have had several stability updates since, so I am going to close this. Let me know if you continue to have issue.
