### ISSUE TITLE
Support for ping

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_runtime#27]
This would be really helpful to have a simple Elixir-based ping command to verify network connectivity as part of the helpers. I'd be fine with another solution that doesn't involve ICMP just so that it works against and access point and doesn't require the Internet to be connected (like wget'ing some web page).

**Comment by electricshaman** [comment]
Question for discussion post-ElixirConf: did we decide against using `ping` from the `iputils` package in Buildroot?

**Comment by fhunleth** [comment]
Against. `ping` is an interactive app and those don't work from the `iex` prompt or the Nerves shell. I'm sure that something could be hacked to make it bearable, but it would probably be more complicated and limited than actually implementing ping. The trick with ping is getting access to raw sockets, but it looks like `:gen_udp` supports them. I've never tried that, but that's the route that I'd take.

p.s. If you ever need commandline `ping` on an embedded system, it's also in `busybox`. Buildroot's default busybox config includes it.

**Comment by electricshaman** [comment]
You had already states on Slack that busybox's ping wouldn't work for our needs so I didn't mention it.

**Comment by fhunleth** [comment]
Closing since helpers can now be found in https://hex.pm/packages/toolshed. There's also a simple ping utility in it.
