### ISSUE TITLE
Move nerves_system_shell to a separate repo?

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_runtime#33]
I've heard mixed reviews of `nerves_system_shell`. My takeaway is that it is not ready for 1.0. The question is to fix or move to a separate repo? I believe that #3 is the primary complaint, but I believe there are other issues that have not been logged.

@electricshaman Since you were the original contributor, do you still use it or have any plans to improve it?

**Comment by electricshaman** [comment]
Yeah, I'll take a look and get back to you on this in the next few days.
