### ISSUE TITLE
Anything that causes a crash of system registry creates  unreadable logs

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_runtime#37]
Not sure if this should go here or in `system_registry`, but the uEvent system causes log barf that makes it impossible to see what happened. 
![peek 2017-11-29 11-06](https://user-images.githubusercontent.com/21150830/33393897-8317f93a-d4f5-11e7-9a1b-1b2d4c87856e.gif)

**Comment by fhunleth** [comment]
Nice touch with the gif. We should make this less verbose.

**Comment by mobileoverlord** [comment]
That error is perfectly descriptive. Its trying to tell you that there's a squirrel in your carburetor

**Comment by fhunleth** [comment]
Closing old issues. Please comment if you'd like to revisit.
