### ISSUE TITLE
Getting to a shell prompt is too much typing

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_runtime#5]
Currently, it's `<Ctrl+G>s 'Elixir.Nerves.Runtime.Shell'<Enter>c<Enter>`. Is there any way we can make this easier?

**Comment by electricshaman** [comment]
I don't think there's any way around the `<Ctrl+G>s '` prefix and `'<Enter>c<Enter>` suffix.

This easiest possible thing would be to rename the module as the shorthand "NRS".  Or

`<Ctrl+G>s 'Elixir.Nerves.Runtime.Shell'<Enter>c<Enter>`
vs.
`<Ctrl+G>s 'Elixir.NRS'<Enter>c<Enter>`

Similarly, another option is to rebrand it as something distinct and more memorable (similar to IEx).
e.g.: Nesh, Nersh, etc.

`<Ctrl+G>s 'Elixir.Nerves.Runtime.Shell'<Enter>c<Enter>`
vs.
`<Ctrl+G>s 'Elixir.Nesh'<Enter>c<Enter>`

Lastly, we could look into compiling the entry point as an Erlang module to remove the `Elixir` root from any of the above options.  It's fairly simple and hands off to `Server.start`.  

`<Ctrl+G>s 'Nesh'<Enter>c<Enter>`

**Comment by fhunleth** [comment]
Yep, I didn't have any ideas off the top of my head, but the typing was annoying enough to throw an issue out there for discussion. I do like your `<Ctrl+G>s 'Nesh'<Enter>c<Enter>` idea. I'd also throw out  `<Ctrl+G>s sh<Enter>c<Enter>` since we're entertaining an Erlang entry points.

**Comment by fhunleth** [comment]
Closing since #9 let you run `<Ctrl+G>s sh<Enter>c<Enter>` to get to the shell.
