### ISSUE TITLE
init.ex documentation question

### ISSUE THREAD

**Issue by deanchouinard** [nerves-project/nerves_runtime#98]
Module doc in init.ex states:

> Since one would expect this to be rare, Nerves systems create firmware images with the do not initialize the application partition so that this code is regularly exercised.

Does it mean? ...create firmware images with un-initialized application partitions...

**Comment by fhunleth** [comment]
Wow, that sentence didn't come out as intended. I'll fix it. To answer your question, we never initialize the application partition when creating SDCards. We rely on the code in `init.ex` to do that.

Thanks for bringing this to my attention.
